source 'https://ruby.taobao.org'

gem 'rails', '4.2.3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'

gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

# Access an IRB console on exception pages or by using <%= console %> in views
gem 'web-console', '~> 2.0', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

# 更友好的出错页面
group :test, :development do
  gem 'better_errors'
  gem 'binding_of_caller'
end

group :test do
  gem 'database_cleaner', '~> 1.4.1'
  gem "factory_girl_rails"
  gem 'capybara'
  gem 'cucumber-rails', :require => false
  gem 'mongoid-rspec', '~> 2.1.0'
  gem 'rspec-rails', '~> 3.0'
end

gem 'mongoid', '~> 4.0.2'
gem 'haml'
gem 'simple_form'
gem 'bootstrap-sass', '~> 3.3.5'

gem 'play_auth', :github => 'mindpin/play_auth',
                 :tag => "0.0.1"

gem 'question_bank', path: '../'
gem 'rails-i18n', '~> 4.0.0'
gem 'simple-navbar', :github => 'mindpin/simple-navbar',
                     :tag => "0.0.7"

gem 'timecop'
gem 'coveralls', require: false, :group => :test
